[package]
name = "samtool"
version = "0.2.7"
edition = "2024"
authors = [ "Shadowdara" ]
readme = "README.md"
description = "the fast cli tool for samfiles"
license = "Apache-2.0"
include = [ "LICENSE", "README.md", "Cargo.toml", "/src/", "buildin.samfile", "build.rs" ]
keywords = [ "samengine", "cli" ]
repository = "https://github.com/shadowdara/seg"

[dependencies]
fluaterm = "0.2.2"
human-panic = "2.0.8"
samfileparser = "0.2.7"
win-utf8-rs = "0.2.1"

[[bin]]
name = "seg"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
debug = 0
incremental = false
