use crate::linksaver::AppConfig;
use std::{
    fs::{self, File},
    io::Write,
    path::Path,
};

/// Function to convert the links file into a Markdown file
pub fn view(config: &AppConfig) {
    let mut file = File::create(".samengine/links.md").unwrap();

    write!(file, "# Links for {}\n\n", config.projectname).unwrap();

    // Add Info Message
    let pfad = Path::new(".samengine/links.info.md");

    if pfad.exists() {
        // add the content to the links file
        let inhalt = fs::read_to_string(".samengine/links.info.md").unwrap();
        let _ = write!(file, "{}\n\n", inhalt);
    } else {
        println!("Info file doesnt exist!");
    }

    let _ = write!(file, "Used for {}: \n\n", config.projectname);

    for l in &config.links {
        let _ = write!(file, "- ");

        if let Some(name) = &l.name {
            let _ = write!(file, "**{}** ", name);
        }

        let _ = write!(file, " ([{}]({})) ", l.link, l.link);

        let _ = write!(file, "- {} - ", l.description);

        if let Some(author) = &l.author {
            let _ = write!(file, "by **{}** ", author);
        }

        if let Some(lic) = &l.license {
            let _ = write!(file, "licensed unter *{}* ", lic);
        }

        if let Some(ll) = &l.licenselink {
            let _ = write!(file, "([{}]({})) ", ll, ll);
        }

        if l.changenotice {
            let _ = write!(file, "- *(changes were made)*");
        }

        if let Some(date) = &l.date {
            let _ = write!(file, " - *(saved at date: {})*", date);
        }

        let _ = write!(file, "\n");
    }

    // for links2
    for l in &config.links2 {
        let _ = write!(file, "- {}\n", l);
    }

    // for links4
    for l in &config.links4 {
        let _ = write!(file, "- {} saved at date: **{}**\n", l.link, l.date);
    }

    // for links3
    for path in &config.links3 {
        if Path::new(path).exists() {
            match fs::read_to_string(path) {
                Ok(content) => {
                    let _ = write!(
                        file,
                        "\n---\n\n**license content from file: {}**\n\n```\n{}\n```\n",
                        path, content
                    );
                }
                Err(e) => {
                    eprintln!("Warning: Could not read '{}': {}", path, e);
                }
            }
        } else {
            eprintln!("Warning: License file '{}' does not exist.", path);
        }
    }

    // for links5
    for path in &config.links5 {
        if Path::new(&path.link).exists() {
            match fs::read_to_string(path.link.clone()) {
                Ok(content) => {
                    let _ = write!(
                        file,
                        "\n---\n\n**license content from file: {}** at date: *{}*\n\n```\n{}\n```\n",
                        path.link, path.date, content
                    );
                }
                Err(e) => {
                    eprintln!("Warning: Could not read '{}': {}", path.link, e);
                }
            }
        } else {
            eprintln!("Warning: License file '{}' does not exist.", path.link);
        }
    }

    let _ = write!(
        file,
        "\n---\n\n*File generated by linksaver from seg* - [More Infos](https://shadowdara.wordpress.com/2026/06/30/minisite-a-site-in-only-one-html-file/)\n"
    );

    println!(
        r#"Created File - Use parseMarkdown from samengine to make it into a nice html file.

npm i samengine
npx samengine markdown .samengine/links.md"#
    );
}

/// Function to convert the links json file into a txt file
pub fn viewx(config: &AppConfig) {
    let mut file = File::create(".samengine/links.txt").unwrap();

    let _ = write!(file, "Links for {}\n\n", config.projectname);

    // Add Info Message
    let pfad = Path::new(".samengine/links.info.txt");

    if pfad.exists() {
        // add the content to the links file
        let inhalt = fs::read_to_string(".samengine/links.info.txt").unwrap();
        let _ = write!(file, "{}\n\n", inhalt);
    } else {
        println!("Info file doesnt exist!");
    }

    let _ = write!(file, "Used for {}: \n\n", config.projectname);

    for l in &config.links {
        if let Some(name) = &l.name {
            let _ = write!(file, "- {}", name);
        }

        let _ = write!(file, " ({}) ", l.link);

        let _ = write!(file, "- {} - ", l.description);

        if let Some(author) = &l.author {
            let _ = write!(file, "by {} ", author);
        }

        if let Some(lic) = &l.license {
            let _ = write!(file, "licensed unter {} ", lic);
        }

        if let Some(ll) = &l.licenselink {
            let _ = write!(file, "({}) ", ll);
        }

        if l.changenotice {
            let _ = write!(file, "- (changes were made)");
        }

        if let Some(date) = &l.date {
            let _ = write!(file, " - (downloaded on the {})", date);
        }

        let _ = write!(file, "\n");
    }

    // for links2
    for l in &config.links2 {
        let _ = write!(file, "- {}", l);
    }

    // for links4
    for l in &config.links4 {
        let _ = write!(file, "- {} saved at date: {}\n", l.link, l.date);
    }

    // for links3
    for path in &config.links3 {
        if Path::new(path).exists() {
            match fs::read_to_string(path) {
                Ok(content) => {
                    let _ = write!(
                        file,
                        "\nlicense content from file: {}\n\n{}\n",
                        path, content
                    );
                }
                Err(e) => {
                    eprintln!("Warning: Could not read '{}': {}", path, e);
                }
            }
        } else {
            eprintln!("Warning: License file '{}' does not exist.", path);
        }
    }

    // for links5
    for path in &config.links5 {
        if Path::new(&path.link).exists() {
            match fs::read_to_string(path.link.clone()) {
                Ok(content) => {
                    let _ = write!(
                        file,
                        "\nlicense content from file: {} at date: {}\n\n{}\n",
                        path.link, path.date, content
                    );
                }
                Err(e) => {
                    eprintln!("Warning: Could not read '{}': {}", path.link, e);
                }
            }
        } else {
            eprintln!("Warning: License file '{}' does not exist.", path.link);
        }
    }

    let _ = write!(
        file,
        "\n---\n\nFile generated by linksaver from samtool - https://shadowdara.wordpress.com/2026/06/30/minisite-a-site-in-only-one-html-file/\n"
    );
}

pub fn list(config: &AppConfig) {
    println!("\nCredits:\n");

    for l in &config.links {
        if !l.showinlist {
            continue;
        }

        println!(
            "\"{}\" ({}) by {} is licensed under {} ({}){}",
            l.name.clone().unwrap_or_default(),
            l.link,
            l.author.clone().unwrap_or_default(),
            l.license.clone().unwrap_or_default(),
            l.licenselink.clone().unwrap_or_default(),
            if l.changenotice {
                " (changes were made)"
            } else {
                ""
            }
        );
    }

    for e in &config.links2 {
        println!("{}", e);
    }
}
