name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary: seg

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: seg.exe

          - os: macos-latest
            target: x86_64-apple-darwin
            binary: seg

          - os: macos-latest
            target: aarch64-apple-darwin
            binary: seg

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - run: cargo build --release --target ${{ matrix.target }}

      - shell: bash
        run: |
          mkdir release
          cp target/${{ matrix.target }}/release/${{ matrix.binary }} release/

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            cd release
            7z a ../${{ matrix.target }}.zip *
          else
            tar -czf ${{ matrix.target }}.tar.gz -C release .
          fi

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
            *.tar.gz
