# Realease seg for all platforms!

name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  # ---------------------------------------------------------
  # Create the GitHub Release first.
  # No GitHub Actions artifacts are used.
  # ---------------------------------------------------------
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
        - name: Verify version
          shell: bash
          run: |
            TAG="${GITHUB_REF_NAME#v}"
            VERSION_NODE=$(node -p "require('./package.json').version")
            VERSION_CARGO=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
            VERSION_TEST=$(python testversion.py)
        
            for SOURCE in \
              "package.json:$VERSION_NODE" \
              "Cargo.toml:$VERSION_CARGO" \
              "testversion.py:$VERSION_TEST"
            do
              NAME="${SOURCE%%:*}"
              VERSION="${SOURCE#*:}"
        
              if [ "$VERSION" != "$TAG" ]; then
                echo "$NAME version ($VERSION) does not match tag ($TAG)"
                exit 1
              fi
            done
    
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true

  # ---------------------------------------------------------
  # Linux builds
  # Ubuntu 20.04 container for glibc compatibility
  # ---------------------------------------------------------
  build-linux:
    name: Build ${{ matrix.target }}
    needs: release
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            binary: seg

          - target: aarch64-unknown-linux-gnu
            binary: seg

          - target: armv7-unknown-linux-gnueabihf
            binary: seg

          - target: riscv64gc-unknown-linux-gnu
            binary: seg

          # Free freebsd
          - target: x86_64-unknown-freebsd
            binary: seg

          # Android
          - target: aarch64-linux-Android
            binary: seg

          - target: armv7-linux-androideabi
            binary: seg

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          apt-get update

          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            curl \
            build-essential \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            pkg-config \
            ca-certificates \
            git \
            tar

      - name: Install Rust
        shell: bash
        run: |
          curl --proto '=https' \
            --tlsv1.2 \
            -sSf https://sh.rustup.rs | \
            sh -s -- -y --default-toolchain stable

      - name: Add Rust target
        shell: bash
        run: |
          source "$HOME/.cargo/env"
          
          rustup target add ${{ matrix.target }}

      # Install cargo cross
      - name: Install cross
        if: |
          matrix.target == 'aarch64-unknown-linux-gnu' ||
          matrix.target == 'armv7-unknown-linux-gnueabihf' ||
          matrix.target == 'riscv64gc-unknown-linux-gnu' ||
          matrix.target == 'x86_64-unknown-freebsd'
        uses: taiki-e/install-action@v2
        with:
          tool: cross
          
      # Runs only on arm
      - name: Configure ARM64 linker
        shell: bash
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          mkdir -p .cargo

          cat > .cargo/config.toml <<'EOF'
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          EOF

      - name: Build native target
        shell: bash
        if: |
          matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          source "$HOME/.cargo/env"
          
          cargo build --release --target ${{ matrix.target }}

      - name: Build cross target
        shell: bash
        if: |
          matrix.target == 'aarch64-unknown-linux-gnu' ||
          matrix.target == 'armv7-unknown-linux-gnueabihf' ||
          matrix.target == 'riscv64gc-unknown-linux-gnu' ||
          matrix.target == 'x86_64-unknown-freebsd'
        run: |
          source "$HOME/.cargo/env"
          
          cross build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          mkdir -p release

          cp \
            target/${{ matrix.target }}/release/${{ matrix.binary }} \
            release/

          tar -czf \
            ${{ matrix.target }}.tar.gz \
            -C release .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ matrix.target }}.tar.gz
          fail_on_unmatched_files: true

  # ---------------------------------------------------------
  # Windows + macOS builds
  # ---------------------------------------------------------
  build-other:
    name: Build ${{ matrix.target }}
    needs: release
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary: seg.exe

          # Windows 32 bit 
          - os: windows-latest
            target: i686-pc-windows-msvc
            binary: seg.exe

          # Windows ARM
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            binary: seg.exe

          # macOS
          - os: macos-latest
            target: x86_64-apple-darwin
            binary: seg

          - os: macos-latest
            target: aarch64-apple-darwin
            binary: seg

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          mkdir -p release

          cp \
            target/${{ matrix.target }}/release/${{ matrix.binary }} \
            release/

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            7z a \
              "${{ matrix.target }}.zip" \
              release/*
          else
            tar -czf \
              "${{ matrix.target }}.tar.gz" \
              -C release .
          fi

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ matrix.target }}.tar.gz
            ${{ matrix.target }}.zip
          fail_on_unmatched_files: false

  # ---------------------------------------------------------
  # Publish npm package
  # ---------------------------------------------------------
  publish-npm:
    name: Publish npm
    needs:
      - build-linux
      - build-other

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - run: npm ci

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  #
  # Publish cargo
  #
  publish-cargo:
    name: Publish Cargo package
    needs:
      - build-linux
      - build-other
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo publish

  # ---------------------------------------
  # Publish pip
  # ---------------------------------------
  publish-pip:
    name: Publish pip package
    needs:
      - build-linux
      - build-other

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: echo "add pip publish herw"
